# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value


#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    home_user.registration.form.type:
        class: Home\BackendBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: home_user_registration }